# Generated by Django 6.0 on 2025-12-23 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_key',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
