# Generated by Django 6.0 on 2025-12-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_remove_choice_id_choice_pk_alter_question_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='topic_id',
            new_name='topic',
        ),
        migrations.RenameIndex(
            model_name='question',
            new_name='questions_q_topic_i_2f996f_idx',
            old_name='questions_q_topic_i_983ca7_idx',
        ),
    ]
