# Generated by Django 6.0 on 2025-12-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_rename_question_id_choice_question_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='question',
            name='questions_q_topic_i_2f996f_idx',
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['topic', 'difficulty'], name='questions_q_topic_i_2f996f_idx'),
        ),
    ]
