# Generated by Django 6.0 on 2025-12-24 08:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0003_remove_choice_id_choice_pk_alter_question_pub_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('mode', models.CharField(choices=[('daily', 'Daily'), ('standard', 'Standard')], default='standard', max_length=128)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answer_sessions.session')),
            ],
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user_id', 'start_at'], name='answer_sess_user_id_df0c0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user_id', 'start_at')},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session_id', 'question_id')},
        ),
    ]
