# Generated by Django 6.0 on 2025-12-24 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useranswer',
            old_name='session_id',
            new_name='session',
        ),
    ]
