# Generated by Django 6.0 on 2025-12-24 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer_sessions', '0002_rename_session_id_useranswer_session'),
        ('questions', '0005_remove_question_questions_q_topic_i_2f996f_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='session',
            name='answer_sess_user_id_df0c0d_idx',
        ),
        migrations.RenameField(
            model_name='session',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='useranswer',
            old_name='question_id',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session', 'question')},
        ),
        migrations.AddField(
            model_name='useranswer',
            name='pk',
            field=models.CompositePrimaryKey('session', 'question', blank=True, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('user', 'start_at')},
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['user', 'start_at'], name='answer_sess_user_id_b93162_idx'),
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='id',
        ),
    ]
